# Generated by Django 4.2.3 on 2023-08-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='customerinfo',
        ),
        migrations.AlterModelTable(
            name='customerinfo',
            table='customerinfo',
        ),
    ]
