# Generated by Django 4.2.3 on 2023-08-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_customer_customerinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicerequest',
            table='servicerequest',
        ),
    ]
