# Generated by Django 4.2.3 on 2023-08-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_customerinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='user',
        ),
    ]
