# Generated by Django 4.2.3 on 2023-08-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_customerinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='first_name',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
