# Generated by Django 4.2.3 on 2023-08-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_servicerequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
